Artificial-Pancreas/iAPS

FreeAPS/Sources/Modules/PreferencesEditor/View/PreferencesEditorRootView.swift
FreeAPS/Sources/Modules/Settings/View/SettingsRootView.swift

iAPS in Setting and Pref

---

fastlane/testflight.md

Aligning GH_PAT with suggestions in LoopDocs:
https://loopkit.github.io/loopdocs/gh-actions/gh-first-time/?h=gh#create-gh_pat

testflight.md: Suggest no expiration for GH_PAT

---

Dependencies/LibreTransmitter/Sources/LibreTransmitter/Bluetooth/LibreTransmitterMetadata.swift
Dependencies/LibreTransmitter/Sources/LibreTransmitter/LibreSensor/SensorContents/PreLibre2.swift
FreeAPS/Sources/APS/CGM/CGMType.swift
FreeAPS/Sources/Modules/CGM/View/CGMSetupView.swift

Ported from the xdripswift repo

New Libre 2 versions. Support for patchInfo starting with "c5"

---

FreeAPS/Sources/Localizations/Main/ar.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/ca.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/da.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/de.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/es.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/fi.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/fr.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/he.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/it.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/nb.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/nl.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pl.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pt-BR.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pt-PT.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/ru.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sk.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/tr.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/uk.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/zh-Hans.lproj/Localizable.strings
FreeAPS/Sources/Modules/CGM/View/CGMRootView.swift

Changed "Configuration CGM" to "CGM Configuration" to make it grammatically correct.

Configuration CGM to CGM Configuration

---

FreeAPS/Sources/APS/FetchAnnouncementsManager.swift

See issue #143 for a description of the problem.
Comments, suggestions and help with testing are very welcome.

Remote announcements proposed fix - Issue #143

---

FreeAPS/Sources/APS/Storage/CarbsStorage.swift
FreeAPS/Sources/Models/CarbsEntry.swift
FreeAPS/Sources/Models/NightscoutTreatment.swift
FreeAPS/Sources/Modules/AddCarbs/AddCarbsStateModel.swift
FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift
FreeAPS/Sources/Modules/DataTable/DataTableDataFlow.swift
FreeAPS/Sources/Modules/DataTable/DataTableStateModel.swift
FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift
FreeAPS/Sources/Services/WatchManager/WatchManager.swift

Add food type note to add carbs view.
Upload of foodType to Nightscout.

Add meal notes (Food Type)

---

fastlane/testflight.md

Typo fixes in FastLane documentation

---

FreeAPS/Sources/APS/Storage/PumpHistoryStorage.swift
FreeAPS/Sources/Localizations/Main/de.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Models/PumpHistoryEvent.swift
FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
FreeAPS/Sources/Modules/DataTable/DataTableDataFlow.swift
FreeAPS/Sources/Modules/DataTable/DataTableStateModel.swift
FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift

* Change all occurances of "Non-Pump" or "nonPump" etc. in texts and code changed to "External"
* Removed label "Automatic" for SMBs in history

Change labels for SMB "Automatic" and "Non-Pump Insulin"

---

FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift

Reverts Artificial-Pancreas/iAPS#287

Revert "Add Swipe-To-Delete Behaviour to History Treatments"

---

FreeAPS/Sources/Localizations/Main/nl.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings

Crowdin updates

---

FreeAPS/Sources/Modules/AddCarbs/AddCarbsStateModel.swift
FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift
FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
FreeAPS/Sources/Modules/Bolus/View/DefaultBolusCalcRootView.swift

New meal view

---

Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
FreeAPS.xcodeproj/project.pbxproj
FreeAPS/Sources/APS/Storage/CoreDataStorage.swift
FreeAPS/Sources/APS/Storage/GlucoseStorage.swift
FreeAPS/Sources/Models/DateFilter.swift
FreeAPS/Sources/Modules/Bolus/BolusProvider.swift
FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
FreeAPS/Sources/Services/WatchManager/WatchManager.swift
FreeAPSWatch WatchKit Extension/DataFlow.swift
FreeAPSWatch WatchKit Extension/WatchStateModel.swift

Use same calculator on Watch as on the iPhone app.

Bolus from watch

---

Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
FreeAPS/Sources/APS/Storage/CoreDataStorage.swift
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
FreeAPS/Sources/Modules/Home/HomeStateModel.swift
FreeAPS/Sources/Modules/Home/View/Chart/MainChartView.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
FreeAPS/Sources/Modules/StatConfig/StatConfigStateModel.swift
FreeAPS/Sources/Modules/StatConfig/View/StatConfigRootView.swift

Configure X-axis (time in hours) from main chart. 
Draft which needs testing.

Add Time buttons under main chart (along button to UX/UI settings)

---

FreeAPS/Sources/Modules/Home/View/Chart/MainChartView.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift

Ref https://github.com/Artificial-Pancreas/iAPS/pull/370#issuecomment-1824574035

Faster hour change

---

.github/workflows/add_identifiers.yml
.github/workflows/create_certs.yml
fastlane/Fastfile

Fastfile changes to support Live Activity

---

FreeAPS/Sources/Models/FreeAPSSettings.swift
FreeAPS/Sources/Modules/NotificationsConfig/NotificationsConfigStateModel.swift
FreeAPS/Sources/Modules/NotificationsConfig/View/NotificationsConfigRootView.swift
FreeAPS/Sources/Services/LiveActivity/LiveActitiyShared.swift
FreeAPS/Sources/Services/LiveActivity/LiveActivityBridge.swift
LiveActivity/LiveActivity.swift

fix mmol live activity, live activity off by default, re-create live activity always after it ended, better readability on lock screen
Fixes #402 
Fixes #403

Live activity fixes

---

.github/workflows/add_identifiers.yml
.github/workflows/build_iAPS.yml
.github/workflows/create_certs.yml
.github/workflows/validate_secrets.yml

See https://github.com/Artificial-Pancreas/iAPS/pull/404 for details

Sync the GitHub runner clock with the Windows time server

---

Dependencies/OmniBLE/OmniBLE/OmnipodCommon/BasalDeliveryTable.swift
Dependencies/OmniBLE/OmniBLE/OmnipodCommon/MessageBlocks/PodInfoTriggeredAlerts.swift
Dependencies/OmniBLE/OmniBLE/PumpManager/OmniBLEPumpManager.swift
Dependencies/OmniBLE/OmniBLETests/PodInfoTests.swift
Dependencies/OmniBLE/OmniBLETests/StatusTests.swift
Dependencies/OmniKit/OmniKit/OmnipodCommon/BasalDeliveryTable.swift
Dependencies/OmniKit/OmniKit/OmnipodCommon/MessageBlocks/PodInfoTriggeredAlerts.swift
Dependencies/OmniKit/OmniKit/PumpManager/OmnipodPumpManager.swift
Dependencies/OmniKit/OmniKitTests/PodInfoTests.swift
Dependencies/OmniKit/OmniKitTests/StatusTests.swift

+ Update all PodInfoTests to compile, cleanly run & make sense
+ Update PodInfoTriggeredAlerts to be only time based triggers
+ Add additional checks & safeguard for temp basal duration

PodInfoTests fixes and improved temp basal checking

---

FreeAPS/Sources/Localizations/Main/ar.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/ca.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/da.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/de.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/el.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/es.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/fi.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/fr.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/he.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/it.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/nb.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/nl.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pl.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pt-BR.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pt-PT.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pt.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/ru.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sk.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/tr.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/uk.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/zh-Hans.lproj/Localizable.strings
FreeAPS/Sources/Modules/NightscoutConfig/View/NightscoutConfigRootView.swift

as well as a pointer to the Statistics / Demographics

Provide a comment for enabling statistics in Nightscout

---

Dependencies/OmniBLE/OmniBLE/OmnipodCommon/MessageBlocks/SetInsulinScheduleCommand.swift
Dependencies/OmniBLE/OmniBLE/PumpManager/PodCommsSession.swift
Dependencies/OmniKit/OmniKit/OmnipodCommon/MessageBlocks/SetInsulinScheduleCommand.swift
Dependencies/OmniKit/OmniKit/PumpManager/PodCommsSession.swift

+ Have SetInsulinScheduleCommand debugDescription display hex nonce values
+ Update OmniBLE programInitialBasalSchedule() to add missing dose append
+ Update OmniBLE recoverUnacknowledgedCommand() to use log.default()
+ Update OmniKit resumeBasal() to omit useless completionBeep parameter
+ Update OmniKit send() beepBlock commenting to match OmniBLE

nonce display & OmniBLE/OmniKit PodCommsSession consistency updates

---

FreeAPS.xcodeproj/project.pbxproj
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
FreeAPS/Sources/Models/Threshold.swift
FreeAPS/Sources/Modules/Dynamic/View/DynamicRootView.swift
FreeAPS/Sources/Views/DescriptionView.swift

New descriptions for the dynamic ISF settings.
New pop-ups, which could be used everywhere in iAPS, also for the OpenAPS settings.
Adjust for dynamic font size and for size of description strings.

Add new descriptions for Dynamic ISF settings and new pop-ups. 

---

FreeAPS/Sources/Modules/Home/View/Header/PumpView.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
FreeAPS/Sources/Views/ViewModifiers.swift

When pump time differs from system time illustrate with overlayed graphics in Home View header.

Display Time Zone Offset

---

FreeAPS/Sources/Modules/OverrideProfilesConfig/OverrideProfilesStateModel.swift

When replacing an active preset Override with a custom override and when replacing preset with another preset, make sure UI and NS is always updated.

Make UI update

---

FreeAPS.xcodeproj/project.pbxproj
FreeAPS/Sources/APS/Storage/CoreDataStorage.swift
FreeAPS/Sources/Modules/Home/HomeStateModel.swift
FreeAPS/Sources/Modules/Home/View/Header/Previews/LoopsView.swift
FreeAPS/Sources/Modules/Home/View/Header/Previews/TIRView.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
FreeAPS/Sources/Modules/OverrideProfilesConfig/OverrideProfilesStateModel.swift

Add Loop statistics for today in Home View.
Add new Loops / Readings percentage, as this is the most important data for evaluating iAPS app status/health. Added to help the Dana developers.
Center align both previews (TIR and Loops).

Preview of Loop Statistics.

---

FreeAPS/Sources/Models/FreeAPSSettings.swift
FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
FreeAPS/Sources/Modules/Bolus/View/AlternativeBolusCalcRootView.swift
FreeAPS/Sources/Modules/Bolus/View/BolusRootView.swift
FreeAPS/Sources/Modules/Bolus/View/DefaultBolusCalcRootView.swift
FreeAPS/Sources/Modules/BolusCalculatorConfig/BolusCalculatorStateModel.swift
FreeAPS/Sources/Modules/BolusCalculatorConfig/View/BolusCalculatorConfigRootView.swift
FreeAPS/Sources/Modules/Home/HomeStateModel.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift

Option to not use any bolus calculator and never wait for any bolus recommendation.

Option to not use any bolus calculator

---

scripts/webpack.config.js

Fix webpack filename generator

Fix webpack filename generator

---

FreeAPS/Sources/Services/ContactTrick/ContactTrickManager.swift

* don't do anything if no contacts configured or access to contacts is not granted
* only save contacts in store if they get changed

Contact Image - small optimizations

---

FreeAPS/Sources/Helpers/UIDevice+Extensions.swift

Few missing phones, mostly new stuff ...

Overdue update to the iPhone identifier list

---

FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift
FreeAPS/Sources/Models/Dynamic structs.swift

Feature request https://github.com/Artificial-Pancreas/iAPS/issues/738

Read override name in middleware

---

FreeAPS/Sources/Modules/Home/View/Header/CurrentGlucoseView.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
FreeAPS/Sources/Modules/Home/View/Previews/ActiveIOBView.swift
FreeAPS/Sources/Modules/Home/View/Previews/LoopsView.swift
FreeAPS/Sources/Modules/Home/View/Previews/TIRView.swift

Make the TIR Preview text annotation position prettier.
Adjust some of the other font sizes to look prettier.

TIR Preview Chart updates

---

FreeAPS/Sources/Modules/Home/View/Previews/TIRView.swift

Use rounding corners.
Position the annotation.

TIR and Loops preview updates.

---

FreeAPS/Sources/APS/OpenAPS/TotalDailyDose.swift
FreeAPS/Sources/Modules/DataTable/DataTableStateModel.swift
FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift

in the pump history data table

Display insulin today (since start of day)

---

FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings

Found non translated strings in my App (Main branch).
Added those from the "sharing" section.
First time doing this ¯\_(ツ)_/¯

Update Localizable.strings - Sharing section

---

Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
FreeAPS.xcodeproj/project.pbxproj
FreeAPS/Sources/APS/OpenAPS/Constants.swift
FreeAPS/Sources/APS/Storage/CoreDataStorage.swift
FreeAPS/Sources/Models/DatabaseModels.swift
FreeAPS/Sources/Models/NightscoutPreferences.swift
FreeAPS/Sources/Models/NightscoutSettings.swift
FreeAPS/Sources/Models/NightscoutStatistics.swift
FreeAPS/Sources/Models/NightscoutStatus.swift
FreeAPS/Sources/Services/Network/Database.swift
FreeAPS/Sources/Services/Network/NightscoutManager.swift
FreeAPS/Sources/Services/Storage/FileStorage.swift

Resolves several old issues with import/upload to Nightscout and to statistics database. 
Prepares for configuration profiles and the onboarding Views coming in v4.9, for instance backup of CoreData.

Prepare for profile switcher coming in version 4.9.

---

FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift

Just run TDD once each loop. 
And add some more printing to console to see time of each oref0 module.

Don't run TDD twice.

---

FreeAPS/Resources/json/defaults/freeaps/freeaps_settings.json
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift
FreeAPS/Sources/Modules/PreferencesEditor/View/PreferencesEditorRootView.swift
FreeAPS/Sources/Modules/PumpSettingsEditor/PumpSettingsEditorStateModel.swift
FreeAPS/Sources/Modules/PumpSettingsEditor/View/PumpSettingsEditorRootView.swift

Many users don't know about this setting, as this was added later to iAPS by request.
Add pop-up description.
Move setting to under Max COB setting.
Lower the default to 200g.

Move max carbs

---

FreeAPS/Sources/APS/Storage/CoreDataStorage.swift
FreeAPS/Sources/Services/Calendar/CalendarManager.swift
FreeAPS/Sources/Services/LiveActivity/LiveActivityBridge.swift

Add support for both open loop mode and closed loop mode.

Live Activity.

---

FreeAPS/Sources/APS/APSManager.swift
FreeAPS/Sources/Services/Calendar/CalendarManager.swift
FreeAPS/Sources/Services/LiveActivity/LiveActivityBridge.swift
LiveActivity/LiveActivity.swift

Add EnactedSuggestionObserver. Do we actually need it, unless just for some corner cases?

Live Activity Updates

---

FreeAPS/Sources/Modules/Home/HomeStateModel.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift

And hide the IOB chart when lacking insulin data.

Hide the COB chart when lacking carb entries.

---

FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
FreeAPS/Sources/Modules/Home/View/Previews/ActiveCOBView.swift
FreeAPS/Sources/Modules/Home/View/Previews/ActiveIOBView.swift

IOB Chart updates: display neg IOB in red and create and add color gradients and lines.
Other Home View updates: Add dividers for header and button panel (just like for any other iOS app).

UI updates

---

.github/workflows/add_identifiers.yml
.github/workflows/build_iAPS.yml
.github/workflows/create_certs.yml
.github/workflows/validate_secrets.yml
fastlane/Fastfile
fastlane/scripts/CreateConfigOverride.sh
fastlane/testflight.md

This allows changing BUNDLE_IDENTIFIER, but could be used for anything that is in Config.xcconfig

Browser Build: ConfigOverride.xcconfig

---

Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
FreeAPS/Sources/Views/ViewModifiers.swift

Update animation duration.
Clean up.

Move infoPanel

---

.github/workflows/syncUpstreamRepo.yml

Missed that build had a run-name: value set .. you can't put a variabkle in the name: field

add run-name: vs name: 

---

FreeAPS/Resources/javascript/prepare/determine-basal.js

Avoid double Override basal adjustment.

---

FreeAPS/Sources/Modules/AutotuneConfig/AutotuneConfigStateModel.swift
FreeAPS/Sources/Modules/AutotuneConfig/View/AutotuneConfigRootView.swift

Save the autotuned basals to pump

Resolve autotune basals

---

FreeAPS.xcworkspace/xcshareddata/swiftpm/Package.resolved
FreeAPS/Sources/Modules/AddCarbs/AddCarbsStateModel.swift
FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift

Swipe right to edit.
Swipe left to delete.

Edit saved food presets.

---

FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift

And add some padding for the button

Avoid line break

---

FreeAPS/Sources/Models/BasalProfileEntry.swift

Fix reading basal json with weird decimal point

---

FreeAPS/Sources/Modules/AutotuneConfig/AutotuneConfigProvider.swift
FreeAPS/Sources/Modules/AutotuneConfig/AutotuneConfigStateModel.swift
FreeAPS/Sources/Modules/AutotuneConfig/View/AutotuneConfigRootView.swift

<details>
<summary>screenshot:</summary>
</details>

autotune view - show current basal rates

---

FreeAPS/Sources/Modules/AutotuneConfig/View/AutotuneConfigRootView.swift

Make current profile matching smarter, when displaying `from -> to` entries.
Also we no longer look at the `start` field (which can fail because sometimes seconds are there, and sometimes they are not).
Copy from discord:
if the autotune period fully fits within a profile period - it will be match
on the screenshots we can see
* the profile entry from `00:00` until `08:00` matches the first 8 autotune suggestions
* the next few profile entries are hour-by-hour - they match the corresponding autotune suggestions (`08:00` until `13:00`)
* the autotune entry at `14:00` does not have a match because in the profile there are two entries: `14:00` .. `14:30` and `14:30` .. `17:30`)
* the autotune entry at `17:00` does not have a match also because there are two entries in the profile that cover …

autotune view - smarter current profile matching

---

FreeAPS.xcodeproj/project.pbxproj
FreeAPS/Sources/Localizations/Main/ar.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/ca.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/da.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/de.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/es.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/fi.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/fr.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/he.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/hu.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/it.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/nb.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/nl.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pl.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pt-BR.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/pt-PT.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/ru.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sk.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/tr.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/uk.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/vi.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/zh-Hans.lproj/Localizable.strings
FreeAPS/Sources/Models/BloodGlucose.swift
FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorDataFlow.swift
FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift
FreeAPS/Sources/Modules/PreferencesEditor/View/PreferencesEditorRootView.swift
FreeAPS/Sources/Views/BGTextField.swift

Display and edit BG values in the preferred units:
* `enableSMB_high_bg_target`
* `halfBasalExerciseTarget`

use selected glucose units in settings 

---

FreeAPS/Sources/Views/ViewModifiers.swift

Request https://github.com/Artificial-Pancreas/iAPS/issues/1021

When pod volume < 15 % change the colour to .red.

---

FreeAPS/Resources/javascript/autoisf/autoisf.js

When using override that include "Override Auto ISF"

Include all FreeAPSSettings properties

---

FreeAPS/Sources/Modules/PumpSettingsEditor/View/PumpSettingsEditorRootView.swift

(because there is a separate Save button)

live editing in the pump settings screen 

---

FreeAPS/Sources/Modules/OverrideProfilesConfig/OverrideProfilesStateModel.swift
FreeAPS/Sources/Modules/OverrideProfilesConfig/View/OverrideProfilesRootView.swift

* Only display the overrides in preset preview - the values overridden. Exclude any values not differing from your ordinary settings.
* Resolve an issue when long pressing
* Display glucose units

Dynamic Profile Previews

---

FreeAPS/Sources/Modules/OverrideProfilesConfig/View/OverrideProfilesRootView.swift
FreeAPS/Sources/Views/ViewModifiers.swift

Use auto horisontal spacing and fixed vertical spacing in preset View to make preset list item layout consistent. Adjust for the bigger BoolTags.
Format using  hours and minutes for the override duration.
Avoid text wrapping
And some other small updates.

Consistent Spacing

---

FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Models/FreeAPSSettings.swift
FreeAPS/Sources/Modules/Home/HomeStateModel.swift
FreeAPS/Sources/Modules/Home/View/Header/CurrentGlucoseView.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
FreeAPS/Sources/Modules/StatConfig/StatConfigStateModel.swift
FreeAPS/Sources/Modules/StatConfig/View/StatConfigRootView.swift

New Setting is in UX/UI settings

Optional display of sensor age (SAGE) in the header View

---

FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift

skip retrieving from storage

---

FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift

A test to resolve issue
https://github.com/Artificial-Pancreas/iAPS/issues/1184

Resolve issue 1184

---

Dependencies/G7SensorKit/G7SensorKitUI/sk.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Localizations/Main/sk.lproj/Localizable.strings

Add missing SK & EN strings

---

FreeAPS/Sources/Localizations/Main/sk.lproj/Localizable.strings
FreeAPS/Sources/Modules/OverrideProfilesConfig/View/OverrideProfilesRootView.swift

Fixed inconsistent item names in profile and added missing quotation mark.

Inconsistent item names

---

Dependencies/G7SensorKit/G7SensorKit/G7CGMManager/G7BluetoothManager.swift
Dependencies/G7SensorKit/G7SensorKit/G7CGMManager/G7CGMManager.swift
Dependencies/G7SensorKit/G7SensorKit/G7CGMManager/G7Sensor.swift

From https://github.com/motinis/G7SensorKit

G7 Fix for missed readings

---

Dependencies/LoopKit/MockKitUI/View Controllers/MockPumpManagerSettingsViewController.swift
Dependencies/LoopKit/MockKitUI/View Controllers/SupportedRangeTableViewController.swift

Refactored hardcoded strings to use LocalizedString

Convert strings to LocalizedString for translation

---

FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings

New string - Display carb equivalent amount

New string

---

Dependencies/G7SensorKit/G7SensorKit/G7CGMManager/G7BackfillMessage.swift
Dependencies/G7SensorKit/G7SensorKit/G7CGMManager/G7BluetoothManager.swift
Dependencies/G7SensorKit/G7SensorKit/G7CGMManager/G7CGMManager.swift
Dependencies/G7SensorKit/G7SensorKit/G7CGMManager/G7Sensor.swift

https://github.com/LoopKit/G7SensorKit/pull/35

 Backport G7 Fix from LoopKit PR#35: Fix calibration decoding, and lagged backfill processing

---

Dependencies/G7SensorKit/G7SensorKit/en.lproj/Localizable.strings
FreeAPS/Sources/Modules/Bolus/BolusProvider.swift
FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
FreeAPS/Sources/Modules/Bolus/View/AlternativeBolusCalcRootView.swift

* Add manual glucose from bolus view, when applicable.
* Resolve issue https://github.com/Artificial-Pancreas/iAPS/issues/1238

Bolus calculator updates

---

FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Models/FreeAPSSettings.swift
FreeAPS/Sources/Modules/NotificationsConfig/View/NotificationsConfigRootView.swift
FreeAPS/Sources/Services/UserNotifiactions/UserNotificationsManager.swift

default notification sound

---

Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift
FreeAPS/Sources/APS/Storage/CoreDataStorage.swift
FreeAPS/Sources/APS/Storage/OverrideStorage.swift
FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
FreeAPS/Sources/Models/FreeAPSSettings.swift
FreeAPS/Sources/Modules/OverrideProfilesConfig/OverrideProfilesStateModel.swift
FreeAPS/Sources/Modules/OverrideProfilesConfig/View/OverrideProfilesRootView.swift

And settings for at what minimum or maximum glucose.
To use for instance when configuring a custom hypo treatment override preset or for a meal preset.
Per request https://github.com/Artificial-Pancreas/iAPS/issues/1387

Profile Override option to end an override when glucose is trending up or trending down

---

README.md

docs: add Dana to README

---

Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift
FreeAPS/Sources/Shortcuts/Meals/MealsShortcuts.swift
FreeAPS/Sources/Shortcuts/OpenClosed/OpenClosedShortcuts.swift

* Resolve Open/Closed Loop Mode shortcut  issue reported in Discord.
Use Picker for when creating automation with open/closed loop mode to make the automation easier.
* Resolve Meal Presets shortcut preset list. Exclude bogus presets.

Resolve shortcut issues

---

FreeAPS/Sources/Models/Autotune.swift
FreeAPS/Sources/Modules/AutotuneConfig/AutotuneConfigStateModel.swift
FreeAPS/Sources/Modules/AutotuneConfig/View/AutotuneConfigRootView.swift

And animate
Fixes issue https://github.com/Artificial-Pancreas/iAPS/issues/895
Also partly fixes another issues discussed in Discord regarding run button, because with new animation it will be clear when autotune is running.

Round Autotune results

---

Gemfile

in case some iAPS-specific changes are needed at some point.

Use fastlane fork

---

FreeAPS/Sources/Shortcuts/SuspendResume/SuspendResumeShortcut.swift

Resolve issue reported in Discord

Shortcut resume/suspend, Use Picker

---

Dependencies/MedtrumKit/MedtrumKit/PumpManager/StateSyncer.swift
Dependencies/MedtrumKit/MedtrumKitUI/ViewModels/Onboarding/PatchPrimingViewModel.swift

Small MedtrumKit fix, so that the prime progressbar does update during priming

fix(MedtrumKit): prime progressbar is now updating

---

Dependencies/MedtrumKit/MedtrumKit/PumpManager/MedtrumPumpManager.swift
Dependencies/MedtrumKit/MedtrumKit/PumpManager/Models/MedtrumActivatePatchResult.swift
Dependencies/MedtrumKit/MedtrumKit/PumpManager/Models/MedtrumPrimePatchResult.swift
Dependencies/MedtrumKit/MedtrumKit/PumpManager/PeripheralManager.swift
Dependencies/MedtrumKit/MedtrumKit/PumpManager/StateSyncer.swift
Dependencies/MedtrumKit/MedtrumKitUI/ViewModels/Onboarding/PatchPrimingViewModel.swift

Changelog:
- Improved error message during priming
- Prevent app crash due to integer overflow
Tagging: @Jon-b-m

fix(medtrum): small bugfixes

---

FreeAPS/Sources/APS/APSManager.swift
FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift
FreeAPS/Sources/APS/Storage/CoreDataStorage.swift
FreeAPS/Sources/Models/ChartModel.swift
FreeAPS/Sources/Models/IOBTick0.swift
FreeAPS/Sources/Modules/Home/HomeProvider.swift
FreeAPS/Sources/Modules/Home/HomeStateModel.swift
FreeAPS/Sources/Modules/Home/View/HomeRootView.swift

A long requested (years) feature.
COB was already updating since earlier iAPS fix.

Update IOB also upon delivery, enacted suggestion and pumpHistory update

---

FreeAPS/Sources/Modules/Home/View/Chart/MainChartView.swift

per request https://github.com/Artificial-Pancreas/iAPS/issues/1202

Colour the glucose dots

---

Dependencies/LoopKit/MockKit/MockPumpManagerState.swift
FreeAPS/Sources/APS/DeviceDataManager.swift
FreeAPS/Sources/Modules/Home/View/Header/PumpView.swift
FreeAPS/Sources/Views/ViewModifiers.swift

Not tested with real pump...
Needs testing
Displays remaining time and units left.

Medtrum header View pump updates

---

.github/workflows/build_iAPS.yml
.github/workflows/create_certs.yml
.github/workflows/syncUpstreamRepo.yml
.github/workflows/validate_secrets.yml
fastlane/Fastfile
fastlane/docs/github.md
fastlane/testflight.md

Update create_certs.yml
Update validate_secrets.yml
Update Fastfile
Update testflight.md
Update github.md (instructions)

Update Distribution certificates and profiles, when needed

---

FreeAPS/Sources/APS/Storage/GlucoseStorage.swift

Remove loop, which shouldn't be needed.
Only log once, to keep logs slimmer.

Glucose storage logging and CGM session start
