Artificial-Pancreas/iAPS

- FreeAPS/Sources/Modules/AddTempTarget/AddTempTargetStateModel.swift
will give full mg/dL targets and mmol/L will just convert fine, also setting in mmol/L works as intended in single decimal digits
> fix rounding to 0 decimals

- FreeAPS/Resources/Assets.xcassets/Colors/Basal.colorset/Contents.json
- FreeAPS/Resources/Assets.xcassets/Colors/TempBasal.colorset/Contents.json
Colour changes only are cherry-picked from https://github.com/mountrcg/freeaps/commit/437ee2edd50acd8844e546ab9c108614f27ca93e
The code for NS "icicle" style basal rendering seems to emerge from mountrcg, but is missing the nice blue colour. This cherry-pick should fix this. It's a lot easier on the eyes, and matches NS.
Current iAPS rendering:
Rendering in this PR:
> NS-style blue basal icicles fill by mountrcg

- .github/workflows/build_iAPS.yml
- fastlane/Fastfile
- fastlane/testflight.md
- Change file name from build_FAX.yml to build_iAPS.yml
- Edit run-name: Build iAPS ${{ github.ref_name }} 
--> displays branch name for Actions runs
> Replace FAX with iAPS in build workflow, instructions and Fastfile 

- .github/workflows/add_identifiers.yml
- .github/workflows/build_iAPS.yml
- .github/workflows/create_certs.yml
- fastlane/Fastfile
- fastlane/testflight.md
This should remove the need to manually set the NFC capability in Apple Developer (https://github.com/Artificial-Pancreas/iAPS/blob/main/fastlane/testflight.md#add-nfc-tag-reading-to-freeeaps-app-id). 
There is little info on this online, so I am unsure if this works correctly (I already have my apps set up). But I have tested that it does not break anything.
It would be good if someone who have not built iAPS with Xcode->TestFlight nor GitHub Actions->TestFlight could verify if the NFC capability will be set by this change.
Also made some other minor changes to the workflows, to avoid pinning the Xcode version, but use the latest stable version available on macos-12 instead.
The changes have been briefly tested and should be safe to merge immediately.
> Add NFC tag reading capability to TestFlight app from Fastfile

- .github/workflows/add_identifiers.yml
- .github/workflows/build_iAPS.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
Use macos-13 (currently in beta) for all workflows, use Xcode 14.3 for build_iAPS.yml
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
Building of iAPS has been briefly verified to work. Icon selection screen is now displayed correctly.
Beta announcement:
https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/
> GitHub Actions build on MacOS 13 / Xcode 14.3

- .github/workflows/build_iAPS.yml
Will upload build-log for more detailed build debug also with failed builds.
Copied from LoopWorkspace
> Always upload artifacts from GitHub Actions build

- FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift
- FreeAPS/Sources/Modules/FPUConfig/View/FPUConfigRootView.swift
An attempt to make FPU more accessible without "always" being displayed.
The toggle is here more of a clickable button. Currently it is displayed as "Use FPU" with blue text, and when active, it is highlighted with black text on blue background. I am open to suggestions for using different colours, or a different text.
The "Use FPU" text is not localized (I don't know how to do that yet).
> Move useFPU toggle from FPUConfigRootView to AddCarbsRootView

- FreeAPS/Sources/APS/CGM/CGMType.swift
Not necessary at all, just a little more precise imho.
When I built to my phone I had to change my CGM in settings to something else and then back to xDrip4iOS, but it's been working without issue since.
> Changed xDrip name to xDrip4iOS in settings

- FreeAPS/Sources/Modules/OverrideProfilesConfig/OverrideProfilesStateModel.swift
ISSUE URL: https://github.com/Artificial-Pancreas/iAPS/issues/141
Currently, after saving a new Profile the code performs an unnecessary conversion of the `target` state variable into `mg/dL` if a user is using `mmol/L` before assigning it to `saveOverride.target`.
The fix removes the conversion and assigns the converted value directly to `saveOverride.target`.
|Before|After
|-|-
|<video src="https://github.com/Artificial-Pancreas/iAPS/assets/17122466/50d46466-6ab1-4d23-b84a-1d9502118925" />|<video src="https://github.com/Artificial-Pancreas/iAPS/assets/17122466/8d4a41ab-87e6-4b81-999a-78dc52c968d5" />
> ISSUE-141 | Fix Target Glucose value after saving a new Profile when units set to mmol/L

- FreeAPS/Sources/Localizations/Main/ar.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/ca.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/da.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/de.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/es.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/fi.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/fr.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/he.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/nl.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/pl.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/pt-BR.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/pt-PT.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/ru.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/sk.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/tr.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/uk.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/zh-Hans.lproj/Localizable.strings
- FreeAPS/Sources/Modules/Settings/View/SettingsRootView.swift
- FreeAPS/Sources/Modules/TargetsEditor/View/TargetsEditorRootView.swift
[ISSUE-161](https://github.com/Artificial-Pancreas/iAPS/issues/161)
- Renamed `Target Ranges` to `Target Glucose`
- Removed unused `Target Ranges` localization string from localization files.
- The app has the `Target Glucose` localization string [here](https://github.com/Artificial-Pancreas/iAPS/blob/dev/FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings#L1296C37-L1296C37) already.
|Settings screen|Target Glucose screen
|-|-
|<img width="564" alt="Screenshot 2023-08-07 at 21 50 17" src="https://github.com/Artificial-Pancreas/iAPS/assets/17122466/e8ed4384-baea-4f67-9144-5edebc4cf255">|<img width="564" alt="Screenshot 2023-08-07 at 21 50 21" src="https://github.com/Artificial-Pancreas/iAPS/assets/17122466/b8c781d3-68e3-47eb-b1e6-bb4e1c2fca66">
> ISSUE-161 | Rename title `Target Ranges` to `Target Glucose`

- FreeAPS/Sources/APS/Storage/PumpHistoryStorage.swift
- FreeAPS/Sources/Models/PumpHistoryEvent.swift
- FreeAPS/Sources/Modules/DataTable/DataTableDataFlow.swift
- FreeAPS/Sources/Modules/DataTable/DataTableStateModel.swift
- FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift
- FreeAPS/Sources/Services/UserNotifiactions/UserNotificationsManager.swift
This PR adds a flag for SMB boluses to the `PumpHistoryStorage` and subsequently alters the treatment history when displaying boluses. For a manual bolus, it displays a blue filled circle with the word "Bolus" and dosage. For an SMB bolus, it displays a blue filled circle, instead of "Bolus" it displays 🤖 and the dosage.
> Add SMB flag for treatment history

- FreeAPS/Sources/Localizations/Main/ar.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/ca.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/da.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/de.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/es.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/fi.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/fr.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/he.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/it.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/nb.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/nl.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/pl.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/pt-BR.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/pt-PT.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/ru.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/sk.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/tr.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/uk.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/zh-Hans.lproj/Localizable.strings
- FreeAPS/Sources/Services/UserNotifiactions/UserNotificationsManager.swift
Changed "Last loop was more th**e**n ..." to "Last loop was more th**a**n"
> ISSUE-257 | Fix typo in `Last loop was more than` message

- FreeAPS/Resources/Assets.xcassets/Colors/Basal.colorset/Contents.json
This PR fixes the display of (temp) basal in the chart for darkmode in iAPS. 
It holds additions contained in PR #236, so that that PR can get smaller. 
**Quoting from PR #236:**
> fixed display of (temp) basal bars in dark mode on home screen, i.e. has proper blue-ish color now
> Fixed chart display of (temp)basal in darkmode

- FreeAPS/Sources/APS/CGM/LibreTransmitterSource.swift
Fixes introduced to patch problems with non-unique ID's in Nightscout accidentally ensured that FSL1 and FSL2 users would no longer see their values (BG) uploaded to Nightscout as they do *not* get a valid UUID.
This commit streamlines the _id field with Dexcom G5, G6 and G7 and ensures it has a unique UUID in compliance with commit https://github.com/Artificial-Pancreas/iAPS/commit/7c7693c05332667efdb4a703aa4fe2cc1f979dca by @avouspierre.
This should fix the problems mentioned by @JohnKitching and @antoinekh under issue https://github.com/Artificial-Pancreas/iAPS/issues/280. 
As I do not have an FSL2, I was unable to verify/test this.
> Fix Nightscout uploads being held back for FSL users

- FreeAPS/Sources/Modules/OverrideProfilesConfig/View/OverrideProfilesRootView.swift
This PR addresses the feature request of #291 and changes the position for the slider numbering so that a finger does no longer block the number when sliding the percentage. 
| Before | After **\*NEW\*** |
|--------|--------|
| <img width="592" alt="image" src="https://github.com/Artificial-Pancreas/iAPS/assets/48965855/17a1a893-40c2-4050-95dd-7bd4ab464703"> | <img width="592" alt="image" src="https://github.com/Artificial-Pancreas/iAPS/assets/48965855/b5c4bd62-4e3f-422c-b191-920d57dc4dae"> |
> Change Profile Editor Slider Numbering Positioning

- FreeAPS/Sources/Modules/AddTempTarget/View/AddTempTargetRootView.swift
This PR changes the slider number positioning for the Temp Target editor to be consistent with the changed positioning of the profile override percentage slider introduced with PR #316. It thereby adheres to feature request as of #291. 
Side notes:
* A little more spacing was also added to give the thumb/finger a bit more screen space to control the slider
* The empty section heading (`Section(header: Text(""))`) was removed to get consistent `Section` spacing.
| Before | After \***NEW\*** |
|--------|--------|
| <img width="592" alt="image" src="https://github.com/Artificial-Pancreas/iAPS/assets/48965855/d59ff110-1004-45d8-9ed2-1580f21521ba"> | <img width="592" alt="image" src="https://github.com/Artificial-Pancreas/iAPS/assets/48965855/18a75e3f-4325-4b33-8f00-1797c4c2dad4"> |
| <img …
> Change Temp Target Slider Numbering Positioning

- Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
- FreeAPS/Sources/APS/DeviceDataManager.swift
- FreeAPS/Sources/APS/Storage/CarbsStorage.swift
- FreeAPS/Sources/Models/CarbsEntry.swift
- FreeAPS/Sources/Models/NightscoutTreatment.swift
- FreeAPS/Sources/Modules/AddCarbs/AddCarbsStateModel.swift
- FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
- FreeAPS/Sources/Modules/Bolus/View/AlternativeBolusCalcRootView.swift
- FreeAPS/Sources/Modules/Bolus/View/DefaultBolusCalcRootView.swift
- FreeAPS/Sources/Modules/DataTable/DataTableProvider.swift
- FreeAPS/Sources/Modules/DataTable/DataTableStateModel.swift
- FreeAPS/Sources/Modules/Home/HomeProvider.swift
- FreeAPS/Sources/Modules/Home/HomeStateModel.swift
- FreeAPS/Sources/Modules/Home/View/Header/LoopView.swift
- FreeAPS/Sources/Modules/Home/View/Header/PumpView.swift
- FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
- FreeAPS/Sources/Services/HealthKit/HealthKitManager.swift
- FreeAPS/Sources/Services/Network/NightscoutAPI.swift
- FreeAPS/Sources/Services/Network/NightscoutManager.swift
- FreeAPS/Sources/Services/WatchManager/WatchManager.swift
- FreeAPS/Sources/Shortcuts/Carbs/CarbPresetIntentRequest.swift
**Update
* Changed this PR with a condition fix and a changed positioning after great feedback on Discord
* Updated images in table below to represent the current look of UI changes in PR
----
This PR adds a small indicator (~~SF Symbol `clock.fill`~~ SF Symbol `clock.badge.exclamationmark.fill` in `.symbolRenderingMode(.multicolor)` with `.warning` as primary and `.red` as secondary colors) that gets displayed ~~in the center of the Loop circle icon~~ next to the pump's or pod's reservoir status when there is an offset between the iPhone's current timezone and the programmed pump time. This usually happens when traveling between timezones or when time's are changed from DST. The icon uses the `.warning` color that is currently also being used when the reservoir gets low on insulin, for …
> Add Timezone Offset Indicator

- FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
This PR addresses concerns over being unable to cancel a bolus due to the icon being too small. This creates a button encompassing the existing text and icon, so users can cancel by tapping either part of the status instead of just the icon. The appearance of the app is unchanged.
> Update Bolus Cancel Button

- fastlane/Fastfile
Adds the branch and last commit to the "What to Test" field in TestFlight to more easily determine the version of each available option in your TestFlight is.
> Add branch+commit to "What to Test" field in TestFlight.

- FreeAPS/Sources/Modules/NightscoutConfig/NightscoutConfigStateModel.swift
Remove trailing slash from Nightscout URL, if entered as such by the user, to prevent 404/"Not Found!" errors due to double slashes in the full URI/path.
This fixes https://github.com/Artificial-Pancreas/iAPS/issues/355. Thanks to @Jon-b-m :)
> Remove trailing slash from NS URL

- FreeAPS/Sources/Modules/NightscoutConfig/NightscoutConfigStateModel.swift
- FreeAPS/Sources/Services/Network/NightscoutManager.swift
Simple changes to make sure that we both import and upload offset values in the proper units.  NS uses seconds, while we use minutes.
Also, changed the importSEttings so that when it imports offset/minutes, it uses the self.offset calculated value, not the value that is pulled from NS ... that eliminates any potential for a mis-match on import
> Fix upload and import functions

- FreeAPS.xcodeproj/project.pbxproj
- FreeAPS/Resources/Info.plist
- FreeAPS/Sources/Application/FreeAPSApp.swift
- FreeAPS/Sources/Assemblies/ServiceAssembly.swift
- FreeAPS/Sources/Models/FreeAPSSettings.swift
- FreeAPS/Sources/Modules/NotificationsConfig/NotificationsConfigStateModel.swift
- FreeAPS/Sources/Modules/NotificationsConfig/View/NotificationsConfigRootView.swift
- FreeAPS/Sources/Services/LiveActivity/LiveActitiyShared.swift
- FreeAPS/Sources/Services/LiveActivity/LiveActivityBridge.swift
- LiveActivity/Assets.xcassets/AccentColor.colorset/Contents.json
- LiveActivity/Assets.xcassets/AppIcon.appiconset/Contents.json
- LiveActivity/Assets.xcassets/Contents.json
- LiveActivity/Assets.xcassets/WidgetBackground.colorset/Contents.json
- LiveActivity/Info.plist
- LiveActivity/LiveActivity.swift
- LiveActivity/LiveActivityBundle.swift
- Only works on iOS 16.2+ because of API availability.
- Includes setting to turn off live activity.
- Live activity is started when the app leaves the active state. Activities can be active for up to 8h. As long as app is opened at least once every 8h, live activity should work continuously.
- Activity turns stale 6m after last bg reading, at which point it will no longer display BG. This is to avoid showing old data. The lock screen and expanded dynamic island view also shows timestamp of displayed BG as further ability to verify that the displayed data is current.
- There have been mentions of using a shortcut + automation to automatically renew live activities in regular intervals. This could be useful to cover cases where the app is not re-opened every 8h. It might work with …
> Live activity

- FreeAPS/Sources/Modules/NightscoutConfig/NightscoutConfigStateModel.swift
This re-introduces a state variable that allows remote control via Nightscout
> Re-add missing state variable for allowing remote control via Nightscout

- .github/workflows/add_identifiers.yml
- .github/workflows/build_iAPS.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
Adding a step to workflow jobs that interface Apple servers, as a workaround for build issues caused by runner clocks being out of sync. See https://github.com/actions/runner issue number 2996 for details.
- name: Sync clock
run: sudo sntp -sS time.windows.com
Added to the following workflows / jobs:
- validate_secrets.yml / validate-fastlane-secrets
- add_identifiers.yml / identifiers
- build_iAPS.yml / build
- create_certs.yml / certificates
> Sync the GitHub runner clock with the Windows time server

- Dependencies/OmniBLE/OmniBLE.xcodeproj/project.pbxproj
- Dependencies/OmniBLE/OmniBLE/PumpManager/PodCommsSession.swift
- Dependencies/OmniKit/OmniKit.xcodeproj/project.pbxproj
- Dependencies/OmniKit/OmniKit/PumpManager/PodCommsSession.swift
+ Verify setup is complete before doing cancel for non-verified pod state
+ Sort files in the Omni{BLE,Kit}/PumpManager directories in Xcode
> Fix a source of possible 0x31 pod faults during pod setup

- FreeAPS.xcodeproj/project.pbxproj
- FreeAPS/Sources/Modules/NotificationsConfig/View/NotificationsConfigRootView.swift
- FreeAPS/Sources/Services/LiveActivity/LiveActitiyShared.swift
- FreeAPS/Sources/Services/LiveActivity/LiveActivityBridge.swift
- LiveActivity/LiveActivity.swift
- Use direction string instead of system icon for trend
- Use semantic colors and improve readability
- Don't hide BG value when data is stale, strikethrough instead
- Prevent flashing live activity briefly when live activities are turned off
- Detect system setting, link to system setting when it is turned off
- Add trend to minimal view (might still get truncated when BG and direction string sum to more than 4 characters)
- Ensure live activity is always started, even when immediately stale
- Fix for iOS < 17
> Live activity updates 2

- Dependencies/OmniBLE/OmniBLE/OmnipodCommon/MessageBlocks/PodInfoActivationTime.swift
- Dependencies/OmniBLE/OmniBLE/OmnipodCommon/MessageBlocks/PodInfoPulseLogPlus.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/OmniBLEPumpManager.swift
- Dependencies/OmniKit/OmniKit/OmnipodCommon/MessageBlocks/PodInfoActivationTime.swift
- Dependencies/OmniKit/OmniKit/OmnipodCommon/MessageBlocks/PodInfoPulseLogPlus.swift
- Dependencies/OmniKit/OmniKit/PumpManager/OmnipodPumpManager.swift
+ Fix implementation bug in PodInfoPulseLogPlus limiting pod time to 9 bits
+ Fix pod pump managers not to crash if an incorrect response type is returned
+ Add safeguards for possible edge cases to prevent 0x31 faults before pod is set up
+ Adjust activationTimeString to better match pulseLogPlusString's output
> More Omnipod pump manager related fixes and improvements

- Dependencies/MinimedKit/MinimedKit/PumpManager/UnfinalizedDose.swift
- Dependencies/OmniBLE/OmniBLE/OmnipodCommon/Pod.swift
- Dependencies/OmniBLE/OmniBLE/OmnipodCommon/UnfinalizedDose.swift
- Dependencies/OmniKit/OmniKit/OmnipodCommon/Pod.swift
- Dependencies/OmniKit/OmniKit/OmnipodCommon/UnfinalizedDose.swift
+ Extend low reservoir notification range
+ Prevent negative duration doses, which can happen if the phone clock is changed
+ Fixes Loop crash when changing time back and cancelling bolus, Loop Issue #2057
> Backport OmniBLE PR #94 & #105, OmniKit PR #9 & #18 and MinimedKit PR #6

- FreeAPS/Sources/Services/WatchManager/WatchManager.swift
- FreeAPSWatch WatchKit Extension/DataFlow.swift
This PR resolves some issues with the data model sent to the Garmin devices.
Added: **glucoseDateInterval** - Simply the numerical date value of the date the last BG was received
Updated: **trendRaw** - Garmin code expects this to be the textual description of the trend and not special characters. 
Fixed a spelling mistake on the function eventualBGString.
> Fixing data model sent over to the Garmin device

- FreeAPS/Resources/json/defaults/freeaps/freeaps_settings.json
- FreeAPS/Sources/Models/FreeAPSSettings.swift
- FreeAPS/Sources/Modules/WatchConfig/View/WatchConfigRootView.swift
- FreeAPS/Sources/Modules/WatchConfig/WatchConfigStateModel.swift
- FreeAPS/Sources/Services/WatchManager/WatchManager.swift
- FreeAPSWatch WatchKit Extension/DataFlow.swift
- FreeAPSWatch WatchKit Extension/Views/BolusConfirmationView.swift
- FreeAPSWatch WatchKit Extension/WatchStateModel.swift
Adds an option in ⚙️>Watch to reduce them amount of turning required of the wheel to confirm a bolus on Apple Watch. Defaults to off.
Tested on live phone and watch (iPhone 14 ProMax/iOS 17.3, SE (2020)/watchOS 10.3)
> Add an option to confirm boluses faster on Apple Watch

- Dependencies/OmniBLE/OmniBLE/OmnipodCommon/Pod.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/OmniBLEPumpManager.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/PodCommsSession.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/PodState.swift
- Dependencies/OmniKit/OmniKit/OmnipodCommon/Pod.swift
- Dependencies/OmniKit/OmniKit/PumpManager/OmnipodPumpManager.swift
- Dependencies/OmniKit/OmniKit/PumpManager/PodCommsSession.swift
- Dependencies/OmniKit/OmniKit/PumpManager/PodState.swift
- Dependencies/OmniKit/OmniKitTests/PodCommsSessionTests.swift
+ Reworked to use new non-persistent lastDeliveryStatusReceived PodState var
+ Remove now unneeded deliveryStatusVerified & lastCommsOK PodState vars
+ Move setupNotComplete error from PumpManagerError to PodCommsError
+ Add new suspended var for DeliveryStatus enum
+ Fix typo in extendedBolusRunning var for DeliveryStatus enum
+ Add new pod setup complete guard to PodCommSession.suspendDelivery()
+ Add new pod setup complete guard to PodCommSession.cancelDelivery()
+ Add new pod setup complete guard to runTemporaryBasalProgram()
+ Rework OmniBLE runTemporaryBasalProgram() to match OmniKit version
+ Update PodState.init() to take an optional initialDeliveryStatus parameter
+ Update PodCommsSessionTests to use new PodState initializer so tests can work
> Backport of missing changes from LoopKit OmniBLE #110 and OmniKit #24

- FreeAPS/Sources/Modules/DataTable/DataTableStateModel.swift
entries in data table and apple health.
- Use default dispatchqueue instead of global to see if this prevents potential race conditions/conflicts
**NOTE!** 
This is just a first test/attempt to adress the reported issue #450 
The bug is very hard to reproduce since it appears intermittently under certain circumstances not yet fully identified. 
More testing is needed to find out if this particular change in queue handling helps or not. ie this PR may or may not solve the issue completely, or only partly if other still unidentified root causes causes the reported bug.
> Test/Attempt to adress and possible fix bug with duplicate carbs..

- Dependencies/OmniBLE/OmniBLE/PumpManager/OmniBLEPumpManager.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/PodCommsSession.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/PodState.swift
- Dependencies/OmniBLE/OmniBLE/PumpManagerUI/ViewControllers/DashUICoordinator.swift
- Dependencies/OmniBLE/OmniBLE/PumpManagerUI/ViewModels/InsertCannulaViewModel.swift
- Dependencies/OmniBLE/OmniBLE/PumpManagerUI/ViewModels/PairPodViewModel.swift
- Dependencies/OmniBLE/OmniBLE/PumpManagerUI/ViewModels/PodLifeState.swift
- Dependencies/OmniBLE/OmniBLE/PumpManagerUI/Views/InsertCannulaView.swift
- Dependencies/OmniKit/OmniKit/PumpManager/OmnipodPumpManager.swift
- Dependencies/OmniKit/OmniKit/PumpManager/PodCommsSession.swift
- Dependencies/OmniKit/OmniKit/PumpManager/PodState.swift
- Dependencies/OmniKit/OmniKitUI/ViewControllers/OmnipodUICoordinator.swift
- Dependencies/OmniKit/OmniKitUI/ViewModels/InsertCannulaViewModel.swift
- Dependencies/OmniKit/OmniKitUI/ViewModels/PairPodViewModel.swift
- Dependencies/OmniKit/OmniKitUI/ViewModels/PodLifeState.swift
- Dependencies/OmniKit/OmniKitUI/Views/InsertCannulaView.swift
UI fixes and improvements for various pod setup restart situations
+ Gracefully handle restarts when prime or insert cannula is in progress
+ Have the view model init funcs test for and handle resume cases
+ Improved PodPairer to include the pumpManager podCommState var
+ Fix PodPairer.podIsActivated to properly handle a paired pod
+ Start with pairAndPrime state when prime has not finalized
+ Update PairPodViewModelState priming value to use an optional
+ Rename func & enum names from pair to pairAndPrime for clarity
+ Improved CannulaInserter to include cannulaInsertionSuccessfullyStarted var
+ For an in-progress insert cannula compute a wait time on remaining bolus
+ Fix checkCannulaInsertionFinished() to use checkingInsertion state
+ Add cannulaInsertionSuccessfullyStarted var to …
> Backport of OmniBLE #113 and OmniKit #27 (fixes Loop issue #2117)

- Dependencies/OmniBLE/OmniBLE/PumpManager/OmniBLEPumpManager.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/PodCommsSession.swift
- Dependencies/OmniBLE/OmniBLE/PumpManagerUI/ViewModels/PairPodViewModel.swift
- Dependencies/OmniKit/OmniKit/PumpManager/OmnipodPumpManager.swift
- Dependencies/OmniKit/OmniKitUI/ViewModels/PairPodViewModel.swift
+ OmniBLE PR122 Prevent hang following restart if Pod Setup was interrupted
+ OmniBLE PR121 Improved Pod Pairing error message
+ OmniBLE PR119 & OmniKit PR33 fix pairing issue introduced with auto pairing retry
+ Skip alert acknowledgements with faulted pod or no active pod (commit within OmniBLE PR118 & OmniKit PR32)
> Back port various Omnipod related fixes from Loop

- .github/workflows/build_iAPS.yml
Prevents GitHub build errors due to your iAPS fork repo name. Allows you to choose any repo name for your iAPS fork when building with GitHub.
> Use any repo name

- FreeAPS/Sources/Models/FreeAPSSettings.swift
Looks like the intention was to have `Sharing` disabled by default, but currently a fresh install of the dev branch defaults `Sharing` to true
This is an incomplete solution, though, since it doesn't address everyone who's already running iAPS and didn't even realize sharing was already defaulted to on. Or they left it on because they never shared their NS with the stats collection website so didn't think it would matter.
Essentially, I think it would be better to rename this setting to fully guarantee anyone sharing their information with the new website is fully aware and doing so intentionally.
(side note: I haven't dug into it much, but from what's been posted, I like the idea for the new way you're collecting stats)
> Disable sharing by default

- FreeAPS/Sources/Services/ContactTrick/ContactPicture.swift
('switch' may only be used as expression in return, throw, or as the source of an assignment)
> fixing a lint

- FreeAPS/Sources/Modules/NightscoutConfig/NightscoutConfigStateModel.swift
Before this PR, two settings were not imported from Nightscout correctly for me.
My 95 mg/dL target glucose got imported as 72 mg/dL (the lowest allowed)
My 58mg/dL ISF got imported as 9 mg/dL
After applying this PR and building to a fresh now simulator, my settings were imported correctly.
> fix importing settings from Nightscout

- FreeAPS/Sources/Modules/ContactTrick/ContactTrickProvider.swift
- FreeAPS/Sources/Services/ContactTrick/ContactTrickManager.swift
Currently, the contacts are only saved into storage when there is a new contact, for which we create an actual contact in the phone Contacts (we store the ID and this triggers the saving into storage).
The bug is this: when an existing contact is edited - the ID is already defined, so the saving into storage does not get triggered.
Here I'm adding a `forceSave: Bool` parameter which is set to `true` when an update is requested from the settings UI.
---
Another small refactoring: removed reading from `storage` from the `ContactTrickProvider` - it now asks the `ContactTrickManager` instead. This makes saving/loading of contacts localized in one place (the manager).
> contact image: fix for saving updates into storage

- FreeAPS/Sources/Modules/TargetsEditor/TargetsEditorStateModel.swift
Bad Swift type conversion.
Workaround: don't change Type.
Swift bug?
Some typos fixed (non-critical).
Remove guard (as not necessary anymore).
> Resolve issue  https://github.com/Artificial-Pancreas/iAPS/issues/712

- FreeAPS/Resources/json/defaults/freeaps/freeaps_settings.json
- FreeAPS/Sources/APS/APSManager.swift
- FreeAPS/Sources/Models/FreeAPSSettings.swift
- FreeAPS/Sources/Modules/Sharing/SharingStateModel.swift
- FreeAPS/Sources/Modules/Sharing/View/SharingRootView.swift
* Fix Typo: birtDate -> birthDate
* Set default birthDate to distantPast ( current default is "today", making everyone an infant )
I tried using distantFuture, but on my simulator, that ended up being May 1, 2024 ... which is the past, not future, which made no sense as the one thing I found online seemed to indicate it should be something like year 4001 ... but the docs themselves show that distant{Past,Future} should both be 'off by centuries', so how it came with this year, no clue.
distantPast is slightly better ... it comes to Jan 1, 1920 ... still not "centuries in the past", but hopefully that is a fixed number, and not floating, so I can filter for that date, with a hopefully pretty good certainty that there aren't a lot of 104 year old users or older that is using iAPS that I am …
> Fix birthDate default / typo

- FreeAPS/Sources/Modules/PumpSettingsEditor/PumpSettingsEditorProvider.swift
- FreeAPS/Sources/Modules/PumpSettingsEditor/PumpSettingsEditorStateModel.swift
I will start by saying: `This is mainly a Dana pump problem`, but the problem is the following:
The LoopKit `syncDeliveryLimits` allows the PumpManager to return DeliveryLimits which are also provided by the parameters. When using Loop (v3.3.0, but this behaviour is since v1.1.0), a dev could return a different then provided and the returned will be stored instead of the provided one. iAPS doesn't do that currently.
Code proof of this behaviour: https://github.com/LoopKit/LoopKit/blob/dev/LoopKitUI/Views/Settings%20Editors/DeliveryLimitsEditor.swift#L348
We need this, because Dana pumps don't allow delivery limits to be set, only to be retrieved. This means that the DanaKit should either:
- Reject every `syncDeliveryLimits` command (which leads to an invalid maxBolus and maxBasal since …
> Fix(PumpManager): Use pump limit from pumpManager instead of UI

- FreeAPS/Resources/javascript/prepare/determine-basal.js
- FreeAPS/Resources/javascript/prepare/middleware.js
- FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift
- FreeAPS/Sources/Models/Charts.swift
- FreeAPS/Sources/Modules/Home/HomeProvider.swift
- FreeAPS/Sources/Modules/Home/HomeStateModel.swift
- FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
- FreeAPS/Sources/Modules/Home/View/Previews/ActiveIOBView.swift
Display insulin analysis in IOB View.
Use the autosens.min/max limits to limit any eventual dynamic basal adjustments.
Use a time adjusted TDD average (real average) for dynamic ISF, to avoid any eventual skewness. 
Example: if current  time is 15:15, your average insulin past 24h (used in dynamic ISF and displayed in IOB View) is the average of all the insulin past 24h entries at this time of day  [today 15:15, yesterday 15:15, day before yesterday 15:15, ... ].
> Insulin and TDD details.

- Dependencies/OmniBLE/OmniBLE/OmnipodCommon/Pod.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/OmniBLEPumpManager.swift
- Dependencies/OmniBLE/OmniBLE/PumpManager/PodCommsSession.swift
- Dependencies/OmniKit/OmniKit/OmnipodCommon/Pod.swift
- Dependencies/OmniKit/OmniKit/PumpManager/OmnipodPumpManager.swift
- Dependencies/OmniKit/OmniKit/PumpManager/PodCommsSession.swift
This PR uses code changes from @itsmojo to address [Trio Issue 244: Critical Pod Fault 049 (0x31) Error When Resuming Insulin Delivery](https://github.com/nightscout/Trio/issues/244#top)
See also [Loop Issue 2121: Bug Report: Eros Pod Fault of 0x31 (-049)](https://github.com/LoopKit/Loop/issues/2121#top), specifically [this comment](https://github.com/LoopKit/Loop/issues/2121#issuecomment-2140997758) 
Bringing this fix to iAPS, which uses the same DASH and Eros drivers.
This updated code is merged into the OmniBLE (`dev`) and OmniKit (`main`) repositories, see PR 123 and PR 35 respectively.
> confirm pod DeliveryStatus to prevent 0x31 fault

- FreeAPS/Sources/APS/APSManager.swift
- FreeAPS/Sources/Application/FreeAPSApp.swift
- FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
- FreeAPS/Sources/Models/Configs.swift
- FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
- FreeAPS/Sources/Modules/Bolus/View/AlternativeBolusCalcRootView.swift
- FreeAPS/Sources/Modules/Bolus/View/BolusRootView.swift
- FreeAPS/Sources/Modules/Bolus/View/DefaultBolusCalcRootView.swift
- FreeAPS/Sources/Modules/Home/HomeStateModel.swift
This will prevent SMBs while entering carbs or while being in bolus view looking at recommendation/predictions, considering doing a manual bolus.
Objective: prevent double boli and prevent any SMBs/basals while testing/viewing/thinking/learning/showing
> Complete the carbs -> bolus flow before enacting any eventual auto bolus (SMB) or any auto temp basal.

- FreeAPS/Resources/javascript/prepare/determine-basal.js
- FreeAPS/Resources/javascript/prepare/profile.js
- FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift
- FreeAPS/Sources/Models/Suggestion.swift
- FreeAPS/Sources/Modules/Home/View/Chart/MainChartView.swift
- FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
Enact a basal rate in middleware. This will be very useful when doing prolonged exercises etc.
New basal rate will be displayed both in pop-up (iAPS pill and in OpenAPS NS pill) and in all other views.
Some UI updates: remove the history button (tapping chart displays history as before) to make more room in button panel.
> Extend middleware function

- FreeAPS/Sources/APS/OpenAPS/TotalDailyDose.swift
- FreeAPS/Sources/Modules/AddCarbs/AddCarbsStateModel.swift
- FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift
- FreeAPS/Sources/Modules/Home/HomeStateModel.swift
- FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
- FreeAPS/Sources/Modules/Settings/View/SettingsRootView.swift
Activate a hypo treatment override preset when selecting *Hypo Treatment* in the meals View. 
The activated override: 45 min, SMBs off, 90%, 6.5 mmol/l target.
This will also skip the Bolus View.
Make the necessary updates to update the override/s in Nightscout.
> Hypo treatments

- FreeAPS/Sources/Services/Calendar/CalendarManager.swift
Resolve Calendar issue introduced in commit af1acf9b2921aef5adb2c1181cbe154214960eb7
> Resolve Calendar issue

- .github/workflows/add_identifiers.yml
- .github/workflows/build_iAPS.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
- fastlane/Fastfile
- fastlane/scripts/CreateConfigOverride.sh
- fastlane/testflight.md
* Add code to allow custom APP_IDENTIFIER
* add APP_IDENTIFIER to list of environment avriables
* make sure we call the right script
* remove before_all as its in wrong place anyway
* add a pwd
* try and fix scripts/CreateConfigOverride.sh
* add denbugging
* add one more
* direct sh call
* Clean out debug command
* add a comment abotu APP_IDENTIFIER to testflight.md
* change comment a bit
> Browser Build: ConfigOverride.xcconfig (#836) PR from @scrappy

- .github/workflows/syncUpstreamRepo.yml
- fastlane/docs/github.md
- fastlane/testflight.md
Once tested, I will extend the docs to add a section to enable.
Its essentially the same instructions as build_iAPS, but until this is in dev, the code is hard coded so that it can run out a separate default branch for testing.
Once tested and in dev, I will change the references to dev to be ${{ github.ref_name }}, and add docs.
Basically, I don't want to advertise until we've confirmed it, *but*, it has to be in dev for us to properly test it ...
sort of a chicken and egg situation.
> Auto sync for with upstream

- .github/workflows/build_iAPS.yml
- fastlane/Fastfile
Tested with both APP_IDENTIFIER set and not set
To test, go into Settings -> Secrets and Variables -> Actions -> Variables tab -> New Repository Variable
Name: APP_IDENTIFIER
Value: new bundle id
The code creates an appropriate ConfigOverride.xcconfig file in the work directory for the build
This code can easily be extended for anything else that would be useful to be in that file
> Allow for non-default Bundle ID

- Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
- FreeAPS/Sources/APS/APSManager.swift
- FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
- FreeAPS/Sources/Localizations/Main/sv.lproj/Localizable.strings
- FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
- FreeAPS/Sources/Modules/Stat/View/StatRootView.swift
- FreeAPS/Sources/Modules/Stat/View/StatsView.swift
Add description pop-up of success rate in statistics View. 
Display number of errors and most frequent cause of loop error in pop-up. 
Display the count of the most frequent loop error.
Save errors with CoreData.
Add localization (new strings to translate).
Animate the LoopsView and the PreviewChart (TIR) while opening the full statistics View.
> More loop statistics.

- Core_Data.xcdatamodeld/Core_Data.xcdatamodel/contents
- FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
- FreeAPS/Sources/Modules/Dynamic/DynamicStateModel.swift
- FreeAPS/Sources/Modules/Dynamic/View/DynamicRootView.swift
Display the average ISF, CR and CSF in Dynamic settings View.
> Average ISF/CR/CSF

- FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
- FreeAPS/Sources/Modules/AddCarbs/AddCarbsStateModel.swift
- FreeAPS/Sources/Modules/AddCarbs/View/AddCarbsRootView.swift
Add a search function for the saved food entries (when more than 4).
Refactor waiter's notepad (cleaner now).
Swipe to delete.
Use carbsRequired as condition for eventual hypo treatment to keep View cleaner. 
Add new button for hypo treatment.
Move "Save as Preset" and "delete preset" to the preset list View for a more compact View.
Lokalize.
> Search saved food presets.

- FreeAPS/Sources/Models/BloodGlucose.swift
- FreeAPS/Sources/Views/BGTextField.swift
- FreeAPS/Sources/Views/DecimalTextField.swift
This changes the way `DecimalTextField` functions:
* it doesn't save the value until the user is done editing (navigate away, switch to other input/control, tap the "Done" button in the toolbar, etc)
* it doesn't mess with what the user is typing (no reformatting, etc)
* it only allows the user to input digits, and at most one decimal separator
* if the final value is not a valid decimal - it will not be saved and the input will reset to the initial value 
Also added the "Cancel" button to the toolbar - it will reset the value to the initial and stop editing.
Should resolve all the issues reported in Discord. Also should improve editing performance - no more lag caused by constant saving into storage.
> DecimalTextField - only save when the user is done editing

- FreeAPS/Sources/Views/DecimalTextField.swift
If the value changes outside of the decimal text field, `textField.text` will get replaced with the new value **even when the user is editing** .
> fix for carbs text field showing 0 after selecting a saved meal

- FreeAPS/Sources/Modules/OverrideProfilesConfig/View/OverrideProfilesRootView.swift
- FreeAPS/Sources/Views/BGTextField.swift
- FreeAPS/Sources/Views/DecimalTextField.swift
The user can tap the "Start" button without leaving the text field they're editing which can (potentially) be a problem:
*  the user will think they changed the value, but it will not be saved
> live editing in all profile override fields

- Dependencies/LoopKit/LoopKit.xcodeproj/xcshareddata/xcschemes/LoopKit Example.xcscheme
- Dependencies/dexcom-share-client-swift/ShareClient.xcodeproj/xcshareddata/xcschemes/Shared-watchOS.xcscheme
- FreeAPS.xcodeproj/project.pbxproj
- FreeAPS.xcodeproj/xcshareddata/xcschemes/FreeAPS X.xcscheme
- FreeAPS.xcodeproj/xcshareddata/xcschemes/FreeAPSWatch.xcscheme
Updated Xcode workspace settings. Makes building quicker and prints less Xcode yellow warnings in console.
CAVE! After this you can't go back easily to previous commits or switch to other branches without these changes (needs a sync with all branches when thoroughly tested).
> Workspace updates

- FreeAPS/Sources/APS/APSManager.swift
- FreeAPS/Sources/Models/TempBasal.swift
due to pump rate ≠ pump history rate
Resolved issue https://github.com/Artificial-Pancreas/iAPS/issues/1160
Round adjusted temp basals before saving.
> Resolve oref0 warning

- FreeAPS/Resources/javascript/prepare/meal.js
- FreeAPS/Sources/APS/OpenAPS/OpenAPS.swift
In oref0 the carb_data are processed in order of the created_at date, however the added carb equivalents in carb_data object were not sorted by this date property. 
However not certain yet, if it really matters...
> Sort carbs by the actual date in oref0

- FreeAPS/Resources/javascript/autoisf/autoisf.js
Making AutoISF respect the target BG from overrides, like ever other part of AutoISF.
> autoisf: bg_isf - respect target BG override

- FreeAPS/Resources/javascript/autoisf/autoisf.js
it seems that sometimes bg_isf is calculated to be very close to 1 but still below it (like 0.999), so in the pill we report `bg: 1`, but the rest of the factors are not evaluated since the code shortcuts on `if (bg_ISF < 1)` - it gets pretty confusing
> autoisf: report bg_isf more precisely (when < 1)

- Dependencies/DanaKit/DanaKit/Packets/DanaBolusStart.swift
change unit from sec/E to sec/U to match pump display; translations are already using sec/U
> change unit from sec/E to sec/U

- .github/workflows/build_iAPS.yml
Manually sets the Xcode version because Xcode 16.0 is selected by default, which is not compatible and causes the build to fail.
> Statically select Xcode 16.3 in GitHub Actions

- FreeAPS/Resources/javascript/autoisf/autoisf.js
Currently, if autoisf is disabled in middleware, the autoisf code is still executed (unless there is ALSO an override active), which causes the `SMB Delivery Ratio` to reset to default `0.5` (ignoring the profile settings).
This PR prevents autoisf from executing when `profile.iaps.autoisf` is set to `false`, regardless if it's disabled by middleware or an override.
> disable autoisf completely when it's disabled by middleware

- FreeAPS/Sources/Modules/Home/View/Chart/MainChartView.swift
A problem reported in Discord turned out to be caused by the following corruption of pump history:
* a `TempBasalDuration` history record without the corresponding `TempBasal` record
* this causes all subsequent TBRs to be missing from the main chart
The reason:
* the `data.tempBasals.chunks` splits the history in chunks of two, expecting each pair to be exactly a `TempBasal` record followed by `TempBasalDuration`, every other pair is ignored
* an orphan `TempBasalDuration` record breaks this expectation completely - the order in the pairs becomes reverted 
The fix:
* to use the `window` function instead of `chunks`, making the procedure resilient to this type of corruption
> basal chart rendering - make more resilient to corrupted data

- FreeAPS/Sources/APS/Storage/PumpHistoryStorage.swift
Fixes #1416
The issue was introduced in this commit (May 2025) - https://github.com/Artificial-Pancreas/iAPS/commit/6279502fbde30523c0a0d535b039522660e43745 (part of this PR: https://github.com/Artificial-Pancreas/iAPS/pull/1348)
The de-duplication logic looks for an existing bolus entry at the exact same timestamp and, if found, replaces it instead of creating a new record. 
The problem is the code is not looking at the type of the existing record and can replace other events instead of boluses - like TBR rate/duration when the timestamp matches exactly. 
I'm not sure if this is possible when using a real pump, but it does happen with the pump simulator (as described in the issue and on Discord).
This PR adds a check such that we only look at "bolus" events when de-duplicating (so the …
> pump history storage - fix bolus de-duplication [fixes #1416]

- FreeAPS/Resources/json/defaults/freeaps/freeaps_settings.json
- FreeAPS/Sources/Localizations/Main/en.lproj/Localizable.strings
- FreeAPS/Sources/Models/FreeAPSSettings.swift
- FreeAPS/Sources/Modules/Bolus/BolusStateModel.swift
- FreeAPS/Sources/Modules/Bolus/View/AlternativeBolusCalcRootView.swift
- FreeAPS/Sources/Modules/Bolus/View/IllustrationView.swift
- FreeAPS/Sources/Modules/BolusCalculatorConfig/BolusCalculatorStateModel.swift
- FreeAPS/Sources/Modules/BolusCalculatorConfig/View/BolusCalculatorConfigRootView.swift
2 new settings (default off).
1: Always use scheduled ISF and CR.
2. Don't use 15 min trend adjustment (per request https://github.com/Artificial-Pancreas/iAPS/issues/1428).
> New Bolus Calculator options

- FreeAPS/Resources/javascript/autoisf/autoisf.js
when running Auto ISF. To avoid having users setting their autosense min/max settings to 1.0.
> Don't use Autosens

- Dependencies/DanaKit/DanaKit/PumpManager/DanaKitPumpManager.swift
DanaKit has a feature, where you can refill the reservoir and/or replace the cannula of your pump, without using the pump's UI. In order to prevent the priming to be stored as a bolus, DanaKit can be put into priming-mode. Due to a coding error, DanaKit did not switch back to a normal mode after a successful prime causing the issue as describe in #1476
> fix(DanaKit): Reset priming mode after completion

- .github/workflows/build_iAPS.yml
- fastlane/Fastfile
I had written the code months ago to allow setting COPYRIGHT_NOTICE via a BUILD_GROUP variable in Github Actions, but failed to export that variable so that Fastlane could use of it.
This corrects that, and adds an output of ConfigOverride.xcconfig step so that its easier to debug going forward
> Export BUILD_GROUP variable from Github Settings -> Fastlane

- FreeAPS/Sources/APS/DeviceDataManager.swift
- FreeAPS/Sources/APS/KnownPlugins.swift
- FreeAPS/Sources/APS/Storage/AlertStorage.swift
- FreeAPS/Sources/Models/AlertEntry.swift
- FreeAPS/Sources/Modules/Home/View/Chart/MainChartView.swift
- FreeAPS/Sources/Modules/PumpConfig/PumpConfigStateModel.swift
- FreeAPS/Sources/Modules/PumpConfig/View/PumpConfigRootView.swift
- FreeAPS/Sources/Services/UserNotifiactions/UserNotificationsManager.swift
* AlertHistoryStorage minor refactoring
* DeviceDataManager - cleanup
* moved more pump-specific code into KnownPlugins
* simplified alert acknowledgement (don't rely on completion callback)
* delivery uncertainty message in pump config view
---
* the whole `PersistedAlertStore` protocol - it's supposed to be used by plugins to query the "storage" about existing alerts, but none of the methods are used in any of the pumps, so we just don't do anything there (same as before the `plugins` branch)
* detectedSystemTimeOffset - we're supposed to report the offset to the pump manager, and loop does have an implementation - but none of the pump managers is using it, we are returning `0` (same as before `plugins`)
* removed the whole `reportPluginInitializationComplete` thing (which I initially …
> more cleanup and refactoring

- FreeAPS/Sources/Modules/Home/View/HomeRootView.swift
Resolves the bolus in progress alert confirmation pop-up not displaying properly with iOS 26
> Fix for iOS 26
